export type QuestType = {
  id?: string,
  // userId?: string,
  domain?: string,
  title?: string,
  description?: string,
  xp_reward?: number,
  duration_seconds?: number,
  status?: string,
  scheduled_at?: string,
  completed_at?: string,
  created_at?: string,
  paused_at?: string,
  started_at?: string,
}